[project]
name = "demo-tiny-effvit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "opencv-python>=4.5.0",
    "mediapipe>=0.10.0",
    "numpy>=1.21.0",
    "torch>=2.0.0",
]

[tool.uv]
dev-dependencies = []
