on:
  push:
    branches: [main]
  pull_request: {}

permissions:
  pull-requests: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile LaTeX (latexmk)
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex
          # set one of these if needed:
          # latexmk_use_xelatex: true
          # latexmk_use_lualatex: true
          # latexmk_shell_escape: true
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: sddec25-01
          path: |
            main.pdf
            references.bib

  chktex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ChkTeX
        uses: j2kun/chktex-action@v2
        with:
          lint-all: true
      - name: Typos (reviewdog)
        uses: reviewdog/action-typos@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
